### ISSUE TITLE
Aware of FileIO.jl?

### ISSUE THREAD

**Issue by juliohm** [JuliaFEM/AbaqusReader.jl#25]
Similar to AsterReader.jl, I am opening an issue to make sure you are aware of the FileIO interface.

It is great to be able to just rely on something like:

```julia
using FileIO

load("filename.extension")
save("filename.extension", data)
```
and let the FileIO package handle the file formats.

**Comment by ovainola** [comment]
Looks interesting, but if I understand correctly it's package, which relies on other packages to handle the file parsing. In the case of finite element models it seems to use MeshIO.jl to parse meshes but there doesn't seem to have any support to read the calculation model / element & node sets.

**Comment by ahojukka5** [comment]
So how in practice we can get AbaqusReader to read ABAQUS .inp files if there is already one registered package?

**Comment by juliohm** [comment]
Thank you for your replies, the idea of FileIO is to unify these loading/saving operations in Julia. For example, I have written a package to load/save GSLIB files, which is a old file format in our field: https://github.com/juliohm/GslibIO.jl

As you can see, from the Julia user point of view, all that is needed is the FileIO package. It will load the GslibIO package whenever someone tries to load a file with *.gslib extension.

If you can do something similar for the FEM-related formats, that would be great. Feel free to close the issue anytime.
