### ISSUE TITLE
Beam elements not supported.

### ISSUE THREAD

**Issue by vjamsa** [JuliaFEM/AbaqusReader.jl#40]
AbaqusReader doesn't support beam elements even though 2 node cubic beams are implemented to JuliaFEM in FEMBeam.jl. The 2 node cubic beam element in space is B33-element in Abaqus.

**Comment by jtveiten** [comment]
We've had some discussion in the past on Gitter on how much support this reader should provide. Look around March 6th.

**Comment by ahojukka5** [comment]
I think it's quite straightforward to read the geometry of beam structure from ABAQUS file, but the properties are the harder one then.

**Comment by vjamsa** [comment]
Im trying to read this input file:
'''
*Node
      1,         240.,        1090.,        147.5
     74,   244.285721,   1114.28577,   173.357147
     75,   248.571426,   1138.57141,   199.214279
     76,   252.857147,   1162.85718,   225.071426
     77,   257.142853,   1187.14282,   250.928574
     78,   261.428558,   1211.42859,   276.785706
     79,   265.714294,   1235.71423,   302.642853
*Element, type=B33
1,  1, 74
2, 74, 75
3, 75, 76
4, 76, 77
5, 77, 78
6, 78, 79
7, 79,  2
'''
And im getting this error message:
'''

LoadError: type Void has no field captures
while loading C:\Users\vjax09\.julia\v0.6\JuliaFEM\examples\f_frame.jl, in expression starting on line 25
in abaqus_read_mesh at JuliaFEM\src\preprocess_abaqus_reader.jl:14
in open at base\iostream.jl:152
in parse_abaqus at AbaqusReader\src\parse_mesh.jl:251
in parse_section at AbaqusReader\src\parse_mesh.jl:133
in regex_match at AbaqusReader\src\parse_mesh.jl:103 
'''

**Comment by ahojukka5** [comment]
I fixed bug related to parsing regexp and B33 element is now supported. See PR #42.
