### ISSUE TITLE
Error due to lowercase elset and nset

### ISSUE THREAD

**Issue by touste** [JuliaFEM/AbaqusReader.jl#48]
If the inp file contains lowercase elset such as:

> *Nset, nset=setEncastre, instance=Part-1-1
> 3,  5,  8, 56, 57, 58, 59, 60, 61, 62, 63

it triggers an error on the `regex_match` function. 

This can be avoided by adding the "i" flag to the regexp string (line 175 of parse_mesh.jl):
> set_regex_string = Dict(:NSET  => r"NSET=([\w\-\_]+)"i,
>                                :ELSET => r"ELSET=([\w\-\_]+)"i )

**Comment by TeroFrondelius** [comment]
> This can be avoided by adding the "i" flag to the regexp string (line 175 of parse_mesh.jl):

Perfect, please make a pull request. You can do such a minor change in the web browser, just find the spot and click the pen icon.

**Comment by touste** [comment]
Actually I just realized that this had already been fixed in the repo, however it still pulls 0.2.2 when I install JuliaFEM.
