### ISSUE TITLE
No support for set names in quotes

### ISSUE THREAD

**Issue by sebastianpech** [JuliaFEM/AbaqusReader.jl#61]
Set names with spaces are put into quotes by abaqus. This is currently not supported by the regex matching mechanism.

Example:
```
*Nset, nset="Outer Coarse"
```

**Comment by TeroFrondelius** [comment]
It would make a reasonable pull request. Can you make it? If you do, also add tests to make sure we won't break anything as well as to test this new feature.

**Comment by sebastianpech** [comment]
sure. I was planning on making one in the next days. For now renaming the set was faster
