### ISSUE TITLE
Support for C3D6

### ISSUE THREAD

**Issue by JTHesse** [JuliaFEM/AbaqusReader.jl#70]
Hi there, I just tried to test the AbaqusReader with a model that I am using. 
Unfortunately it seems that C3D6 elements are currently not supported.

Will those elements be supported in a future release or is this project currently on hold?
Thank you!

**Comment by JTHesse** [comment]
Ok just saw the last commit, it's already included. Will there be a new release though?

**Comment by ahojukka5** [comment]
@JuliaTagBot release

**Comment by JTHesse** [comment]
Thank you, @ahojukka5, but the release wasn't triggered. Also, I added a [pull request](https://github.com/JuliaFEM/AbaqusReader.jl/pull/71), is there time for you to look into that or is this package not updated anymore? We would really like to use this package in our software, only the few element types and maybe the verbose option is missing.

**Comment by ahojukka5** [comment]
@JuliaRegistrator register

**Comment by ahojukka5** [comment]
I fixed, let's try again...

**Comment by ahojukka5** [comment]
@JuliaRegistrator register

**Comment by ahojukka5** [comment]
Ok now the new version should be merged soon.

**Comment by JTHesse** [comment]
Thank you!
